# Default initial positions for rosie_V1's ros2_control fake system

initial_positions:
  fl_wheel_joint: 0
  fr_wheel_joint: 0
  head_pan_joint: 1.0
  left_arm_0: 0
  left_arm_1: 0
  left_arm_2: 0
  left_arm_3: 0
  left_arm_4: 0
  left_arm_5: 0
  left_arm_6: 0
  left_finger_joint: 0
  right_arm_0: 0
  right_arm_1: 0
  right_arm_2: 0
  right_arm_3: 0
  right_arm_4: 0
  right_arm_5: 0
  right_arm_6: 0
  right_finger_joint: 0
  rl_wheel_joint: 0
  rr_wheel_joint: 0
  torso_5: 0