sensors:
  - pointcloud
  - depth_image

pointcloud:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: depth_pclsa
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 3.0
    max_update_rate: 1.0
    resolution: 0.05  # Added resolution for Octomap
    filtered_cloud_topic: filtered_points

